### ISSUE TITLE
Removed to binary string support

### ISSUE THREAD

**Issue by pavelthq** [nodeca/pako#218] opened 2021-02-16 23:47 UTC
Hello, 

My question is about removed functionality to get binary string.

I would say it was cool feature, and it is very useful for using pako.deflate while making requests to server.

How we used it: base64.encode(pako.deflate(data, {to:'string'})).
Then in backend side (php) we used base64_decode zlib decode and it worked perfectly, the requests sizes in total was like 30% less size than sending raw string (not zipped).

Since v2.0 we see that to:string is removed, and it always returns Uint8array which even after join (comma separated numbers) is larger than just regular json.stringify so it is useless to use it as the request size is larger than raw.

So my statement is that this functionality should be returned.

Thanks for your work. 👍

**Comment by puzrin** [comment] 2021-02-17 19:38
Dupe of #206

**Closed by puzrin** 2021-02-17 19:38 UTC
