### ISSUE TITLE
Error: invalid distance too far back

### ISSUE THREAD

**Issue by yupkey** [nodeca/pako#236] opened 2021-08-30 10:15 UTC
This issue is present with large size data. Please update zlib version to at least 1.2.9 to fix that issue. 
https://github.com/madler/zlib/blob/master/ChangeLog

**Comment by puzrin** [comment] 2021-08-30 10:51
Isn't this dupe of https://github.com/nodeca/pako/issues/139#issuecomment-724176722?

Could you provide example how to reproduce (if not dupe), or refer to commit in upstream with fix?

**Comment by yupkey** [comment] 2021-08-30 11:53
I have to set `chunkSize` option in order to work with large data
`pako.inflate(new Uint8Array(compressed), { to: 'string', chunkSize: 1024*1024 })`
Thanks for linking to #139

**Closed** 2021-08-30 11:53 UTC
