### ISSUE TITLE
Difference in deflating Chinese between index.js(npm package) and pako.min.js

### ISSUE THREAD

**Issue by tuif** [nodeca/pako#161] opened 2019-02-21 10:19 UTC
It seems deflate could produce different results for Chinese. e.g.:
        pako.deflate('中')

If we use pako.min.js, it would be,
Uint8Array(11) [120, 156, 91, 187, 227, 9, 0, 4, 94, 2, 74]

If we use index.js(packed by webpack), it would b,
Uint8Array(11) [120, 156, 123, 178, 99, 45, 0, 4, 204, 2, 74]

The latter would be correct, since it can be inflated to the original

**Comment by tuif** [comment] 2019-02-21 10:30
it occurs in 1.0.8. 1.0.6 is fine.

**Comment by puzrin** [comment] 2019-02-21 12:09
This is dupe of #158 (see explanations there). Encode deflate input to utf8 first (then back on inflate).

**Comment by tuif** [comment] 2019-02-21 13:40
Got it. It's wired that index.js and pako.min.js has different behaviors...

**Comment by puzrin** [comment] 2019-02-21 13:52
It would be useless waste of time to discuss "different behaviour" for incorrect calls. Fix your code, then if problem still exists - create new issue.

**Comment by puzrin** [comment] 2019-02-21 13:55
https://github.com/nodeca/pako/commit/6e78b394311733a86d487e89583235c5e27e70d3

There was browserify version update in `1.0.8`, but i'm not sure it can affect correct code (and nobody cares about incorrect one).

**Comment by tuif** [comment] 2019-02-21 16:13
Not sure. Guess it's minify-related error of string2buf, since string2buf is quite correct, comparing to TextEncoder result.

**1. Minified version of string2buf**
function A(t){var e,a,i,n,r,s=t.length,o=0;for(n=0;n<s;n++)55296==(64512&(a=t.charCodeAt(n)))&&n+1<s&&56320==(64512&(i=t.charCodeAt(n+1)))&&(a=65536+(a-55296<<10)+(i-56320),n++),o+=a<128?1:a<2048?2:a<65536?3:4;for(e=new l.Buf8(o),n=r=0;r<o;n++)55296==(64512&(a=t.charCodeAt(n)))&&n+1<s&&56320==(64512&(i=t.charCodeAt(n+1)))&&(a=65536+(a-55296<<10)+(i-56320),n++),e[r++]=a<128?a:(e[r++]=a<2048?192|a>>>6:(e[r++]=a<65536?224|a>>>12:(e[r++]=240|a>>>18,128|a>>>12&63),128|a>>>6&63),128|63&a);return e;}

A('中')
Uint8Array(3) [173, 184, 228]
**2. Original version of string2buf**
string2buf('中')
Uint8Array(3) [228, 184, 173]

**3. TextEncoder text code**
A('中')
Uint8Array(3) [228, 184, 173]

**Comment by puzrin** [comment] 2019-02-21 16:19
Please, fix your input data (to be 8-bits, like utf8), prior to post any considerations. If you wish to deflate strings, those MUST be BINARY strings, not any JS (utf-16) string. Discussing what happens with broken input is a bit out of scope, imho.

**Comment by tuif** [comment] 2019-02-22 00:08
Already fixed fixed input with your information. Thank.
But if it's a really minifiy-related error, it perhaps occur in others function sooner or later.

**Comment by puzrin** [comment] 2019-02-22 00:22
You try to analyze things, named as "undefined behaviour". I respect your right to spend your personal time as you wish, but can not participate :)

**Comment by rejoc** [comment] 2019-02-28 19:35
in Deflate.push there is code to handle the case where 'data' id string. In this case, you call strings.string2buf. 

And here is the issue. 

When you call this string2buf function with an utf-8 character like → (right arrow), it returns an array [226, 134, 146]. That's what was expected.

Now, if you do the same with the minified version, you get [146, 134, 226]. (the array is filled up backward)

(the 2nd for loop of this function is messed up by the minification process)

So the issue is in the minification process!! So stop providing a minified version ;-)

**Comment by puzrin** [comment] 2019-02-28 19:42
> there is code to handle the case where 'data' id string

Pako NEVER annouced to process "any strings". Only "BINARY strings". This may cause confusion, but that's not pako and not minifier fault. If you wish, you can try PR with better explanations in README. Also, there is example with detailed comments about data reencoding.

Pako (zlib) process BINARY data to BINARY data. Everything else is a bit out of project scope IMHO.

**Comment by puzrin** [comment] 2019-02-28 19:46
> When you call this string2buf function with an utf-8 character like → (right arrow), it returns an array [226, 134, 146]. That's what was expected.

> Now, if you do the same with the minified version, you get [146, 134, 226]. (the array is filled up backward)

Hm... do i understand you right, that you provide utf-8 encoded input data (correct binary string, as requested), but minified version sucks?

**Comment by rejoc** [comment] 2019-02-28 20:12
Yes. The minified version you provide fill up the buffer in reverse order. I've just tried to minifiy with this tool https://javascript-minifier.com and the result works well.

The issue is that the minification tools replace the 
```
    if (c < 0x80) {
      /* one byte */
      buf[i++] = c;
    } else if (c < 0x800) {
      /* two bytes */
      buf[i++] = 0xC0 | (c >>> 6);
      buf[i++] = 0x80 | (c & 0x3f);
    } else if (c < 0x10000) {
      /* three bytes */
      buf[i++] = 0xE0 | (c >>> 12);
      buf[i++] = 0x80 | (c >>> 6 & 0x3f);
      buf[i++] = 0x80 | (c & 0x3f);
    } else {
      /* four bytes */
      buf[i++] = 0xf0 | (c >>> 18);
      buf[i++] = 0x80 | (c >>> 12 & 0x3f);
      buf[i++] = 0x80 | (c >>> 6 & 0x3f);
      buf[i++] = 0x80 | (c & 0x3f);
    }
```
with (in your version) [i tried to indent the code to be more readable)
```
 e[r++] = a<128 ? a : 
	     (e[r++] = a < 2048 ? 192 | a>>>6 : 
		    (e[r++] = a < 65536 ? 224 | a >>> 12 :
			   (e[r++] = 240 | a>>>18,128 |a>>>12&63), 128 | a>>>6&63),128|63&a)
```
Here it seems obvious that the r++ are done from right to left

In the version I've tested  you get something like: 
```
e<128 ? t[n++] = e : 
	    e<2048 ? (t[n++] = 192 | e>>>6, 
		          t[n++]=128|63&e) : 
				    e<65536 ? 
				      (t[n++]= 224 | e>>>12 ,
					   t[n++]=128|e>>>6 &63, 
					   t[n++]=128|63&e) :
					     (t[n++]=240|e>>>18,
						  t[n++]=128|e>>>12&63,
						  t[n++]=128|e>>>6&63,
						  t[n++]=128|63&e);
```

**Comment by puzrin** [comment] 2019-02-28 20:25
Thank you for details. Could you test latest 1.0.9 version? It was released by different reason, but with fresh deps install. May be, problem eliminated? If not - i will start deps rollback process.

**Comment by puzrin** [comment] 2019-02-28 21:10
Hm... seems i forgot myself how pako works, and it really support JS strings somehow :). Sorry for mess.

Good news is, that i reprodused problem (see added test). Will try to find working version of uglify-js and roll back.

**Comment by puzrin** [comment] 2019-02-28 21:44
https://github.com/mishoo/UglifyJS2/issues/3278

Released 1.0.10, hope it's fixed now.

**Closed** 2019-02-28 21:47 UTC
Labels: bug

**Comment by rejoc** [comment] 2019-02-28 21:48
Thanks :-)

**Comment by tuif** [comment] 2019-03-01 05:43
Good news, thanks very much!
