### ISSUE TITLE
inflate/deflate is not a function (wrangler)

### ISSUE THREAD

**Issue by AtroCty** [nodeca/pako#203] opened 2020-11-18 21:54 UTC
Hello everyone,

since I updated pako 2.0.11 (from 1.0.11) I received this in my service when I create a POST-request.

```
worker.js:1 Uncaught (in promise) TypeError: i.deflate is not a function
    at Object.callback (worker.js:1)
    at t.exports.handleRequest (worker.js:1)
    at worker.js:1
(anonymous) @ worker.js:1
handleRequest @ worker.js:1
(anonymous) @ worker.js:1
Promise.catch (async)
(anonymous) @ worker.js:1

```
Same happens to inflate. As soon as I downgraded back to 1.0.11 it worked again. 
I use the Cloudflare worker-service together with wrangler.

Best regards

**Comment by puzrin** [comment] 2020-11-18 22:34
Porbably dupe of 202. Please note, if you create issue, you are expected to provide minimalistic info how to reproduce problem, without reference to your app.

**Closed by puzrin** 2020-11-18 22:34 UTC
