### ISSUE TITLE
zlib result != pako result

### ISSUE THREAD

**Issue by dduponchel** [nodeca/pako#65] opened 2015-09-10 20:23 UTC
I found a raw deflated content that fails the unit test, see https://github.com/dduponchel/pako/commit/d7cfa458acf13d322df4ba3a9fd248109418e168.
See also https://github.com/Stuk/jszip/issues/184. This issue has other examples of failed inflate but this one is the smallest.
As the comment says, it works in v0.2.3, not after.

**Comment by puzrin** [comment] 2015-09-10 20:33
Hm... looks strange, because we changed wrapper only after 0.2.3.

@andr83 said he will take a look at weekend.

**Comment by puzrin** [comment] 2015-09-13 11:13
@dduponchel take a look at temporary patch in branch https://github.com/nodeca/pako/tree/issue-65. Does it helps with all broken samples or something still does not work?

Will release a bit later, need to discuss some tech issues about this hack.

**Comment by dduponchel** [comment] 2015-09-13 14:27
That fixed the issue with the sample I gave but not with the other samples. I added them all in https://github.com/dduponchel/pako/commit/b1c4b0301599bb447a021adaeea5e94e719814a7.

**Comment by puzrin** [comment] 2015-09-13 14:34
Thanks for info. This regression  happened after #29 fix. Need to think how to do both and keep code clear.

**Comment by puzrin** [comment] 2015-09-14 12:23
All should be properly fixed now in 0.2.8

**Closed by puzrin** 2015-09-14 12:23 UTC

**Comment by puzrin** [comment] 2015-09-14 12:24
Added you to "thanks" section https://github.com/nodeca/pako#authors :)
