### ISSUE TITLE
Failing to inflate a sequence of bytes

### ISSUE THREAD

**Issue by photopea** [nodeca/pako#174] opened 2019-09-24 10:00 UTC
Deflate is used in a PDF format for lossless compression. 

A PDF file has been sent to me with a following sequence of 6419 bytes: "file.log".

When I try to inflate them with my own library [UZIP.js](https://github.com/photopea/UZIP.js), I get 71731 bytes: "file.txt".

Also, the PDF file can be displayed with [pdf.js](https://github.com/mozilla/pdf.js), and Adobe Reader (both seem to have their own Deflate implementations).

pako.js fails on this sequence of bytes, showing "Uncaught invalid distance too far back"
[file.log](https://github.com/nodeca/pako/files/3646576/file.log)
[file.txt](https://github.com/nodeca/pako/files/3646578/file.txt)

**Comment by puzrin** [comment] 2019-09-25 03:59
I don't understand what to do with this how is that related to pako. Do you have small executable code sample, proving that problem is really at pako side?

**Comment by photopea** [comment] 2019-09-25 08:13
The problem is, that pako.js can not do Deflate decompression. Could you fix it?

    var buf = new Uint8Array([88, 133, 205, 93, 219, ...]);  // the content of file.log
    var bytes = pako.inflate(buf);  // throws an error

**Comment by puzrin** [comment] 2019-09-25 08:33
If you came with statement about pako bug, i need proof. Because

- input may be invalid.
- wrong function  may be used (inflate <=> inflateRaw) and so on.

Current info is not enougth. For example, you could create test repo with node.js script, and use node's built-in zlib method. Also see #139.

**Comment by photopea** [comment] 2019-09-25 09:06
I thought you would trust me a bit more :P  As I said before, it is a valid ZLIB stream, that is accepted by three different ZLIB implementations.

Anyway, I made this demo:  view-source:http://www.ivank.net/veci/pako_test.html

Look at the source code and the console output. As you can see, UZIP.js and zlib.js process it well, while pako.js crashes.

**Comment by puzrin** [comment] 2019-09-25 09:21
Can this be a dupe of #139?

There were posted workarounds in issie and branch. But one strange test fails, and nobody can remember what it does :).

**Comment by photopea** [comment] 2019-09-25 09:27
It is hard to tell, if the bugs are related.

I am just providing a valid input, for which, pako.js does not provide a correct output.

But if pako.js is a port of ZLIB library, then, the bug is either in ZLIB itself, or in the way you rewrote it to Javascript (I guess the second one is more probable).

**Comment by puzrin** [comment] 2019-09-25 09:34
Not necessary. Refered burg is in wrapper, zlib port itself is correct.

**Comment by photopea** [comment] 2019-09-25 10:11
You are right!  If I slice 2 bytes from the beginning and 4 bytes from the end of the sequence, pako.inflateRaw() works correctly!

The first byte = 88 = 0101 1000 defines the LZ77 window size of 8192 Bytes. I guess the Deflate stream inside uses a larger size for compression.  Could you just ignore these two bytes and always use the window size of 32 768 Bytes?

**Comment by puzrin** [comment] 2019-09-25 10:20
Sound reasonable. Could you try add `| 15` here to the end https://github.com/nodeca/pako/blob/master/lib/inflate.js#L137 ?

**Comment by photopea** [comment] 2019-09-25 10:42
I am sorry, I am quite busy at the moment :(

I don't really need pako.js , as I replaced it by my own library UZIP.js . I just thought you might want to know about this bug.

**Comment by puzrin** [comment] 2019-09-25 10:49
No problem. I will add fix a bit later. Thank you for your help!

**Comment by puzrin** [comment] 2019-09-26 05:49
I digged sources, this can not be fixed without diverging zlib port from upstream.

1. https://github.com/nodeca/pako/blob/master/lib/zlib/inflate.js#L482 - hear length is taken from header AND next line skip window size set if `windowBits` option passed before.
2. https://github.com/nodeca/pako/blob/master/lib/zlib/inflate.js#L491 - but hear max distance still based on header value.

https://github.com/madler/zlib/blob/master/inflate.c#L699 - upstream has the same behaviour.

If first bytes replaced to [120, 156] (max window + updated header crc), inflate works

**Comment by puzrin** [comment] 2019-09-26 05:50
Since following mainstream is more important than autofixing mailformed header, i'd prefer leave everything as as.

**Comment by RenaKunisaki** [comment] 2020-10-10 21:19
So what am I to do when I get this problem with data that I know to be valid but don't control?

**Comment by puzrin** [comment] 2020-11-06 21:09
@RenaKunisaki you can apply raw inflate manually, for example.

**Comment by RenaKunisaki** [comment] 2020-11-07 01:01
How do I do that?

**Closed** 2020-11-13 17:26 UTC
Labels: wontfix
